version: '3.8'

services:
  app:
    build: .
    tty: true
    env_file:
      - env/app.env
    volumes:
      - .:/code
    ports:
      - "8000:8000"
      - "8080:8080"
    expose:
      - 8000
      - 8080
    depends_on:
      - db
    # command: sh -c "python manage.py runserver 0.0.0.0:8000"

  db:
    image: postgres:16
    volumes:
      - data-volume:/var/lib/postgresql/data
    environment:
      - TZ=Asia/Tokyo
    env_file:
      - env/db.env

volumes:
  data-volume:
  