services:
  app:
    container_name: stall-rental-system-app
    build: .
    tty: true
    working_dir: /code
    env_file:
      - env/app.env
    volumes:
      - ./code:/code
    ports:
      - "8080:8080"
    expose:
      - 8080
    depends_on:
      - db

  db:
    container_name: stall-rental-system-db
    image: postgres:16
    volumes:
      - data-volume:/var/lib/postgresql/data
    environment:
      - TZ=Asia/Tokyo
    env_file:
      - env/db.env

volumes:
  data-volume:
  